version: '2.3'
services:
   torch-notebook:
    container_name: ${USER}-iaflash
    build:
      context: ./docker/torch-notebook
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
    runtime: nvidia
    ipc: host
    cpus: 8
    env_file:
      - docker/env.list
    environment:
     - NVIDIA_VISIBLE_DEVICES=1
     - TORCH_MODEL_ZOO=/model
     - http_proxy=${http_proxy}
     - https_proxy=${http_proxy}
     - no_proxy=${no_proxy}
    ports:
     - "8887:8888"
     - "9997:5000"
    volumes:
     - /data:/data
     - /data:/workspace/iaflash/data
     - /home/dss:/dss
     - /home/model:/model
     - /home/notebooks:/workspace
     - ./:/workspace/iaflash
     - /home/notebooks/.jupyter:/root/.jupyter
    command: "jupyter notebook --ip=0.0.0.0 --no-browser --allow-root --notebook-dir=./"
