version: '2.3'
services:
   torch-notebook:
    container_name: ${USER}-iaflash-refactor
    build:
      context: .
      dockerfile: ./docker/torch-notebook/Dockerfile
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
    runtime: nvidia
    ipc: host
    cpus: 16
    env_file:
      - docker/env.list
    environment:
     - NVIDIA_VISIBLE_DEVICES=0,1,2,3
     - TORCH_MODEL_ZOO=/model
     - http_proxy=${http_proxy}
     - https_proxy=${http_proxy}
     - no_proxy=${no_proxy}
    ports:
     - "${NOTEBOOK_PORT}:8888"
     - "${APP_PORT}:5000"
    networks:
     - isolated_nw
    volumes:
     - /data:/data
     - /vgdata:/vgdata
     - /data:/workspace/iaflash/data
     - /home/dss:/dss
     - /home/model:/model
     - /home/notebooks:/workspace
     - ./:/workspace/iaflash
     - /home/notebooks/.jupyter:/root/.jupyter
    command: "jupyter notebook --ip=0.0.0.0 --no-browser --allow-root --notebook-dir=./"



networks:
  isolated_nw:
    external:
     name: isolated_nw
