version: '3.8'
services:
   iaflash-notebook:
    container_name: ${USER}-iaflash
    image: iaflash-detectron2:v1
    build:
      context: .
      dockerfile: ./docker/torch-notebook/Dockerfile-detectron2
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
    runtime: nvidia
    ipc: host
    cpus: 16
    env_file:
      - docker/env.list
    environment:
     - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES}
     - CUDA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES}
     - TORCH_MODEL_ZOO=/model
     - http_proxy=${http_proxy}
     - https_proxy=${http_proxy}
     - no_proxy=${no_proxy}
    ports:
     - "${NOTEBOOK_PORT}:8888"
     - "${APP_PORT}:5000"
    networks:
     - isolated_nw
    volumes:
     - /data:/data
     - /vgdata:/vgdata
     - /home/dss:/dss
     - /home/model:/model
     - /home/notebooks:/notebooks
     - ./:/workspace/iaflash
     - /home/notebooks/.jupyter:/root/.jupyter
    command:
      - /bin/sh
      - -c
      - |
          python3 ./iaflash/app/app.py &
          jupyter notebook --ip=0.0.0.0 --no-browser --allow-root --notebook-dir=/notebooks

networks:
  isolated_nw:
    external:
     name: isolated_nw
