---
name: Publish documentation

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Publish documentation

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip uninstall pandas
          pip install Pillow==5.3.0 Flask==1.0.2 numpy==1.16.2 pandas==0.24.2 requests==2.21.0 vertica-python==0.9.0 scrapy==1.6.0 psycopg2-binary pytest==5.1.1 Sphinx==2.0.1 sphinx-autodoc-typehints==1.6.0 sphinx-rtd-theme==0.4.3 matplotlib
          pip install -e .
      - name: Build documentation
        run: |
          make -C ./docs html
          touch ./docs/build/html/.nojekyll
      - name: deploy
        uses: docker://peaceiris/gh-pages:v2.3.2
        if: success()
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./docs/build/html
